### GET all activities
GET http://localhost:3000/api/activities
### POST a new activity
POST http://localhost:3000/api/activities
Content-Type: application/json

{
  "name": "Test Activity 2",
  "tags": [
    {
      "name": "Test Tag 2",
      "color": "#32a852"
    }
  ]
}
### DELETE an activity
DELETE http://localhost:3000/api/activities/1773921587185
###